### ISSUE TITLE
invariant violation:607,"RCTView ", 91,{overflow:'hidden','height':'<<NAN>>'}} is not usable as native method argument.

### ISSUE THREAD

**Issue by vtrioremya** [hamidhadi/react-native-collapsible-list#3]
![Simulator Screen Shot - iPhone XS - 2019-03-19 at 14 01 58](https://user-images.githubusercontent.com/43376141/54591128-9558b000-4a4f-11e9-86e0-557760ff8f9c.png)
This is my code where is used collapasile-view.

import React, {Component} from 'react';
import {Platform, ScrollView, StyleSheet,TouchableOpacity, Text, View, Image, FlatList, Dimensions} from 'react-native';
import Search from '../Components/Search'
import ClickTab from '../Components/ClickTab'
import HeaderNav from '../Components/HeaderNav'
var {height, width} = Dimensions.get('window');
import {  Icon } from 'react-native-elements';
import CollapsibleList from 'react-native-collapsible-list'

type Props = {};
export default class Television extends Component<Props> {

  constructor(props){
    super(props);
    this.state = {

    };
  }

  render() {
    return (

      <View style={styles.container}>
        <CollapsibleList numberOfVisibleItems={1}>
          <View style={styles.collapsibleItem}>
            <Text>Hello Collapsable List :)</Text>
          </View>
          <View style={styles.collapsibleItem}>
            <Text>Collapsable List Item</Text>
          </View>
          <View style={styles.collapsibleItem}>
            <Text>Collapsable List Item</Text>
          </View>
        </CollapsibleList>
      </View>
      );
    }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  collapsibleItem:{
    // width:width,
    // height:100,
    borderBottomWidth: 2,
    borderColor: '#CCC',
    padding: 10
  }
});
Please help!

**Comment by atitpatel** [comment]
Try giving an initial value animation state variable in the library.

For eg.

`animation: new Animated.Value(0)`

**Comment by hamidhadi** [comment]
@vtrioremya Sorry for the late response!🤦🏻‍♂️
I'm looking for a time to rewrite this project. Implementation of animations can be much simpler and less buggy.😃 
I'll release a new version end of next week.
Have a nice coding!😉

**Comment by Babar-Memon** [comment]
> I am getting same issue Did you find any solution ?

Try giving an initial value animation state variable in the library.

For eg.
  animation: new Animated.Value(1)

**Comment by hamidhadi** [comment]
Sorry guys for the late response. I just updated the `v2.0.0` of this repo. Please read the doc to know the new changes and upgrade it in your project to fix this issue.

**Comment by harsha-kotapati** [comment]
Invariant Violation: [1795,"RCTView",{"bottom":"<<Infinity>>"}] is not usable as a native method argument  

>   

![simulator_screenshot_28D2A381-EB33-4A4B-B6A7-347DCD471AC6](https://user-images.githubusercontent.com/70576078/108809147-35210000-75ce-11eb-869d-da3868e8f56f.png)
