### ISSUE TITLE
How to make Button Fixed on Top

### ISSUE THREAD

**Issue by akiladevinda** [hamidhadi/react-native-collapsible-list#5]
How to make toggle button fixed on top ? Now it's goes down with the collapse. I want to make button fixed on top of the list

**Comment by akiladevinda** [comment]
EDIT ->

I do it by editing the index.js file return view as bellow

    return (
      <View style={wrapperStyle}>
        {numberOfVisibleItems < React.Children.count(children) && (
          <View>
            <TouchableOpacity onPress={() => this.toggle()} activeOpacity={0.8}>
              {buttonContent}
            </TouchableOpacity>
          </View>
        )}
        <View style={{ overflow: "hidden", height: currentHeight }}>
          <View
            style={{ flex: 1 }}
            onLayout={event => this.setMinHeight(event)}
          >
            {React.Children.toArray(children).slice(0, numberOfVisibleItems)}
          </View>
          {initialized && (
            <View>
              {React.Children.toArray(children)
                .slice(numberOfVisibleItems)
                .map((item, index) => (
                  <View key={index}>{item}</View>
                ))}
            </View>
          )}
        </View>
      
      </View>
    );

**Comment by hamidhadi** [comment]
Hey @akiladevinda 👋 
This functionality is now available via props.
Thanks for your idea 😉
