### ISSUE TITLE
List Closes Automatically Immediately

### ISSUE THREAD

**Issue by Sanan4li** [hamidhadi/react-native-collapsible-list#7]
I tried the example you have added but when I click the button. List expands but collapses withing a second automatically.
Any solution?

**Comment by hamidhadi** [comment]
Hey @Sanan4li 👋 
I couldn't reproduce that. Could you please post your codes here?

**Comment by Sanan4li** [comment]
> Hey @Sanan4li 👋
> I couldn't reproduce that. Could you please post your codes here?

its been 4 days... I used "react-native-collapsible/Accordion" instead.
